version: '3.8'

services:
  # app:
  #   container_name: nestjs
  #   build: .
  #   volumes:
  #     - .:/usr/src/app
  #     - /usr/src/app/node_modules
  #   ports:
  #     - "3300:3300"
  #   networks:
  #     - echrnetwork
  #   depends_on:
  #     - postgres

  postgres:
    image: postgres
    container_name: conference-scheduler-db
    environment:
      POSTGRES_DB: conference-scheduler
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:


