export enum ErrorCode {
  USER_CREATE_FAILED = 'USER_CREATE_FAILED',
  USER_CREATE_FAILED_EMAIL = 'USER_CREATE_FAILED_EMAIL',
  USER_NOT_FOUND = 'USER_NOT_FOUND',
  SCHEDULED_MEET_NOT_FOUND = 'SCHEDULED_MEET_NOT_FOUND',
  MEET_ALREADY_EXISTS = 'MEET_ALREADY_EXISTS',
  USER_NOT_CREATOR = 'USER_NOT_CREATOR',
  NOT_ENOUGH_PERMISSIONS = 'NOT_ENOUGH_PERMISSIONS',
}
